version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of sample data provided by dbt, s3://dbt-tutorial-public/jaffle_shop_customers.csv
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer.
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.